stages:
  - build
  - test
  - deploy

variables:
  DIST_ART_DIR: "dist"
#  DIST_PREFIX: "${CI_PROJECT_NAME}"
  DIST_EXT: "tar.gz"
  DIST_INSTALLED_DIR: "${CI_PROJECT_NAME}"
  ARCHIVE_TOOL: "tar czvf"
  UNARCHIVE_TOOL: "tar xvf"
  ARCHIVE_EXT: "tar.gz"
#  ARCHIVE_NAME: "${DIST_PREFIX}-unknown.${ARCHIVE_EXT}"
  GH_TOOL_URL: https://ci.espressif.cn:42348/cache
  GH_TOOL_NAME: github-release
  GH_TOOL: "./${DIST_ART_DIR}/${GH_TOOL_NAME}"
  GITHUB_USER: antmak
  GITHUB_REPO: "${CI_PROJECT_NAME}"
#  RELEASE_DESC: "New release, long-awaited fixes"

.get_release_name: &get_release_name |
  REL_VERSION=$(git describe --tags | sed -n -r "s|${CI_PROJECT_NAME}-(.*)|\1|gp")
  REL_NAME=${CI_PROJECT_NAME}-${PLATFORM_NAME}-${REL_VERSION}
  ARCHIVE_NAME=${REL_NAME}.${DIST_EXT}
  echo "PLATFORM_NAME: $PLATFORM_NAME"
  echo "REL_VERSION: $REL_VERSION"
  echo "REL_NAME: $REL_NAME"
  echo "ARCHIVE_NAME: $ARCHIVE_NAME"

.dist_archive: &dist_archive |
  ${ARCHIVE_TOOL} ${ARCHIVE_NAME} ${DIST_INSTALLED_DIR}
  mkdir -p ${DIST_ART_DIR}
  mv ${ARCHIVE_NAME} ${DIST_ART_DIR}
  echo "${ARCHIVE_NAME}" > ${DIST_ART_DIR}/dist_name_${PLATFORM_NAME}

before_script:
  # add gitlab ssh key (on Linux only)
  - >
    test $(uname -s) != "Darwin" &&
    echo "Setting up Gitlab SSH key" &&
    mkdir -p ~/.ssh &&
    chmod 700 ~/.ssh &&
    echo -n $GITLAB_KEY > ~/.ssh/id_rsa_base64 &&
    base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa &&
    chmod 600 ~/.ssh/id_rsa &&
    echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # reconfigure submodules
  - git config submodule.tools/git2cl.url $GITLAB_SSH_SERVER/idf/git2cl.git
  - git config submodule.jimtcl.url $GITLAB_SSH_SERVER/idf/jimtcl.git
  - git config submodule.src/jtag/drivers/libjaylink.url $GITLAB_SSH_SERVER/idf/libjaylink.git
  - set -o errexit; set -o pipefail; set -o nounset
  - set -x
  # Gitlab doesn't clean submodule contents
  - (cd tools/git2cl && git clean -fxd) || true
  - (cd jimtcl && git clean -fxd) || true
  - (cd src/jtag/drivers/libjaylink && git clean -fxd) || true
  # remove Github remote, if configured
  - git remote rm github || true
  # OpenOCD configuration options
  - "export OPENOCD_CONFIGURE_OPTS=\"
        --disable-doxygen-html
        --disable-doxygen-pdf
        --enable-ftdi
        --enable-jlink
        --enable-ulink
    \""

build_linux:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-toolchain
  tags:
    - build
  artifacts:
    paths:
      - ${DIST_ART_DIR}
    expire_in: 2 weeks
  variables:
    PLATFORM_NAME: "linux64"
  script:
    - *get_release_name
    - git submodule update --init
    - ./bootstrap
    - ./configure --prefix=$PWD/$DIST_INSTALLED_DIR $OPENOCD_CONFIGURE_OPTS
    - make -j `nproc`
    - make install-strip
    - *dist_archive

.build_windows:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-toolchain-win-cross
  tags:
    - build

  artifacts:
    paths:
      - dist
    expire_in: 2 weeks

  variables:
    GIT_STRATEGY: fetch

  script:
    # Build libusb-1.0
    - export LIBUSB_VER=libusb-1.0.21
    - wget https://dl.espressif.com/dl/$LIBUSB_VER.tar.gz -O $LIBUSB_VER.tar.gz
    - tar xzf $LIBUSB_VER.tar.gz && rm $LIBUSB_VER.tar.gz
    - pushd $LIBUSB_VER
    - ./bootstrap.sh
    - ./configure --prefix=$PWD/dist  --host=i686-w64-mingw32 --enable-shared=no --enable-static=yes
    - make -j `nproc`
    - make install-strip
    - export PKG_CONFIG_PATH=$PWD/dist/lib/pkgconfig
    - popd
    # Build OpenOCD
    - git submodule update --init
    - ./bootstrap
    - ./configure --prefix=$PWD/openocd-esp32 --host=i686-w64-mingw32 $OPENOCD_CONFIGURE_OPTS
    - make -j `nproc`
    - make install-strip
    - cp /usr/i686-w64-mingw32/lib/libwinpthread-1.dll openocd-esp32/bin/
    - export REL_NAME=openocd-esp32-win32-`git describe --always`
    - zip -r $REL_NAME.zip openocd-esp32/
    - mkdir -p dist
    - mv $REL_NAME.zip dist/


.build_macos:
  stage: build
  image: $CI_DOCKER_REGISTRY/osxcross
  tags:
    - build

  artifacts:
    paths:
      - dist
    expire_in: 2 weeks

  variables:
    GIT_STRATEGY: fetch

  script:
    # Osxcross comes with a no-op symlink for pkg-confg,
    # remove it and install pkg-config.
    # TODO: prepare a Docker image which would have it included.
    - rm -f `which x86_64-apple-darwin12-pkg-config`
    - wget https://dl.espressif.com/dl/pkg-config_0.28-1_amd64.deb
    - dpkg -i ./pkg-config_0.28-1_amd64.deb

    # Build bootstrap tcl interpreter.
    # TODO: include 'tcl' package into the docker image instead
    - cp -r jimtcl jimtcl-bootstarp
    - pushd jimtcl-bootstarp/
    - ./configure --prefix=$PWD/local
    - make -j `nproc`
    - make install
    - popd

    # Cross-compile libusb-1.0 for OSX
    - export LIBUSB_VER=libusb-1.0.21
    - wget https://dl.espressif.com/dl/$LIBUSB_VER.tar.gz -O $LIBUSB_VER.tar.gz
    - tar xzf $LIBUSB_VER.tar.gz && rm $LIBUSB_VER.tar.gz
    - pushd $LIBUSB_VER
    - ./bootstrap.sh
    - ./configure --prefix=$PWD/dist --host=x86_64-apple-darwin12 --enable-shared=no --enable-static=yes CC=x86_64-apple-darwin12-cc
    - make -j `nproc`
    - make install
    - popd

    # Finally, cross-compile OpenOCD
    - export PKG_CONFIG_PATH=$PWD/$LIBUSB_VER/dist/lib/pkgconfig
    - ./bootstrap
    - ./configure --prefix=$PWD/openocd-esp32 --host=x86_64-apple-darwin12 $OPENOCD_CONFIGURE_OPTS LDFLAGS="-Wl,-framework,CoreFoundation -Wl,-framework,IOKit" CC=x86_64-apple-darwin12-cc
    - make -j `nproc`
    - make install-strip

    # Package release archive
    - export REL_NAME=openocd-esp32-macos-`git describe --always`
    - tar czvf $REL_NAME.tar.gz openocd-esp32/
    - mkdir -p dist
    - mv $REL_NAME.tar.gz dist/

.push_master_to_github:
  stage: deploy
  only:
    - master
  when: on_success
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  before_script:
    - echo "not switching submodules to Gitlab"
    - git remote rm github || true
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GH_PUSH_KEY > ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git remote add github git@github.com:espressif/openocd-esp32.git
    - git push github HEAD:master

.build_test_app:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  tags:
    - build

  artifacts:
    paths:
      - testing/esp/test_apps/gen_ut_app/output/default/gen_ut_app.elf
      - testing/esp/test_apps/gen_ut_app/output/default/gen_ut_app.bin
      - testing/esp/test_apps/gen_ut_app/output/default/partitions_singleapp.bin
      - testing/esp/test_apps/gen_ut_app/output/default/bootloader/bootloader.bin
      - testing/esp/test_apps/gen_ut_app/output/single_core/gen_ut_app.elf
      - testing/esp/test_apps/gen_ut_app/output/single_core/gen_ut_app.bin
      - testing/esp/test_apps/gen_ut_app/output/single_core/partitions_singleapp.bin
      - testing/esp/test_apps/gen_ut_app/output/single_core/bootloader/bootloader.bin
    expire_in: 2 weeks

  script:
      # Prepare ESP-IDF
      - rm -rf esp-idf
      - git clone $GITLAB_SSH_SERVER/idf/esp-idf.git
      - pushd esp-idf
      - tools/ci/mirror-submodule-update.sh
      - export IDF_PATH=$PWD
      - popd
      # Build generic test app
      - pushd testing/esp/test_apps/gen_ut_app
      - make ut-apply-config-default
      - make V=1 ut-build-default
      - make ut-apply-config-single_core
      - make V=1 ut-build-single_core
      - popd

.run_autotests:
  stage: test
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  tags:
    - test_jtag

  allow_failure: true

  artifacts:
    paths:
      - testing/esp/debug_backend_tests.log
    when: always
    expire_in: 1 week

  script:
      # Run tests
      - mkdir -p dist/tmp
      - pushd dist/tmp
      - tar xzvf ../openocd-esp32-linux64-*.tar.gz
      - export DIST_DIR=$PWD/openocd-esp32
      - popd
      - pushd testing/esp
      - ./run_tests.py -o $DIST_DIR/bin/openocd -s $DIST_DIR/share/openocd/scripts -a $PWD/test_apps -d 4 -l ./debug_backend_tests.log
      - popd
